Create Warfarin.cpp
现在报错会给出一个错误编码比如

Warfarin Virtual Machine has spotted an error has occured. ERROR CODE: 3
RuntimeError:  type Null doesn't support operate '+'.

把这个错误代码复制下来输入到errhelp.exe中就可以得到错误帮助信息了